targets:
  $default:
    sources:
      exclude:
        - bin/*.dart
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
      drift_dev:
        options:
          databases:
            app_db: lib/models/database/database.dart
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
